"use client";

import { usePathname } from "next/navigation";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ThemeToggle } from "@/components/theme-toggle";
import { Toaster } from "@/components/ui/toaster";
import {
  SidebarProvider,
  SidebarInset,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { Separator } from "@/components/ui/separator";
import { LogoutButton } from "@/components/logout-button"; // Importa LogoutButton

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function RootLayout({ children }) {
  const pathname = usePathname();

  // Rotte dove non vogliamo mostrare la sidebar
  const noSidebarRoutes = ["/"];

  const showSidebar = !noSidebarRoutes.includes(pathname);

  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          {showSidebar ? (
            <SidebarProvider>
              {/* Sidebar principale */}
              <AppSidebar />
              {/* Sidebar con header e contenuto principale */}
              <SidebarInset>
                <header className="flex h-16 shrink-0 items-center justify-between border-b px-4 ">

                  {/* Separator */}
                  <Separator orientation="vertical" className="h-6 bg-gray-600 mx-4" />

                  {/* Pulsanti Logout e ThemeToggle */}
                  <div className="flex items-center space-x-4">
                    <ThemeToggle />
                    <LogoutButton />
                  </div>
                </header>
                <main className="p-6 md:p-10">{children}</main>
              </SidebarInset>
            </SidebarProvider>
          ) : (
            <main className="flex min-h-screen items-center justify-center">
              {children}
            </main>
          )}
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
